language: node_js
node_js:
  - "9"
cache:
  yarn: true
  directories:
    - node_modules
install:
#  - yarn
script:
  - cp ./config/local.example.json ./config/local.json
  - NODE_ENV=development npm test
  - rm ./config/local.json
services:
  - docker
before_install:
  - docker build -t humanconnection/api-feathers:alpha .
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push humanconnection/api-feathers:alpha;
    fi
#  - yarn run coverage